# Generated by Django 4.2 on 2023-04-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TProducto', models.CharField(max_length=100, verbose_name='Tipo del producto')),
            ],
            options={
                'verbose_name': 'Tipo del producto',
                'verbose_name_plural': 'Tipos de producto',
                'db_table': 'tproducto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('CanActProducto', models.PositiveIntegerField(null=True, verbose_name='Cantidad de productos en bodega')),
                ('PrecioProducto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta por unidad')),
                ('NumProdPedidos', models.PositiveIntegerField(null=True, verbose_name='Número de productos por debajo del cual se debe hacer un nuevo pedido al laboratorio')),
                ('TipoProducto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DrogueriaApp.tipoproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
    ]
